### ISSUE TITLE
FATAL: Unknown resource error : undefined method `downcase'  executing catalog list

### ISSUE THREAD

**Issue by riccardopulcini** [chef/knife-vrealize#44]
### Versions
* Version of 
* knife-vcenter (2.0.8)
* knife-vrealize (4.0.3)
* knife-vsphere (4.0.5)
* Chef Workstation version: 0.11.21
* Chef Infra Client version: 15.4.45
* Chef InSpec version: 4.18.0
* Chef CLI version: 2.0.0
* Test Kitchen version: 2.3.4
* Cookstyle version: 5.10.13

### Platform Details
* Version of vRA: 7.0

### Scenario
get the catalog from vra 

### Steps to Reproduce
execute 'knife vra catalog list'

### Expected Result
the catalog list

### Actual Result
FATAL: Unknown resource error : undefined method `downcase' for nil:NilClass
Traceback (most recent call last):
        17: from C:/opscode/chef-workstation/bin/knife:370:in `<main>'
        16: from C:/opscode/chef-workstation/bin/knife:370:in `load'
        15: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.4.45-universal-mingw32/bin/knife:24:in `<top (required)>'
        14: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.4.45-universal-mingw32/lib/chef/application/knife.rb:162:in `run'
        13: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.4.45-universal-mingw32/lib/chef/knife.rb:228:in `run'
        12: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.4.45-universal-mingw32/lib/chef/knife.rb:484:in `run_with_pretty_exceptions'
        11: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.4.45-universal-mingw32/lib/chef/local_mode.rb:42:in `with_server_connectivity'
        10: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.4.45-universal-mingw32/lib/chef/knife.rb:485:in `block in run_with_pretty_exceptions'
         9: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/knife-cloud-2.0.3/lib/chef/knife/cloud/command.rb:50:in `run'
         8: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/knife-cloud-2.0.3/lib/chef/knife/cloud/list_resource_command.rb:38:in `execute_command'
         7: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/knife-cloud-2.0.3/lib/chef/knife/cloud/list_resource_command.rb:79:in `list'
         6: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/knife-cloud-2.0.3/lib/chef/knife/cloud/list_resource_command.rb:79:in `each'
         5: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/knife-cloud-2.0.3/lib/chef/knife/cloud/list_resource_command.rb:83:in `block in list'
         4: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/knife-cloud-2.0.3/lib/chef/knife/cloud/list_resource_command.rb:62:in `get_resource_col_val'
         3: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/knife-cloud-2.0.3/lib/chef/knife/cloud/list_resource_command.rb:62:in `each'
         2: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/knife-cloud-2.0.3/lib/chef/knife/cloud/list_resource_command.rb:63:in `block in get_resource_col_val'
         1: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/knife-cloud-2.0.3/lib/chef/knife/cloud/list_resource_command.rb:63:in `call'
C:/Users/Administrator/AppData/Local/chefdk/gem/ruby/2.6.0/gems/knife-vrealize-4.0.3/lib/chef/knife/vra_catalog_list.rb:59:in `format_status_value': undefined method `downcase' for nil:NilClass (NoMethodError)

**Comment by mcascone** [comment]
I am seeing this same issue. We are upgrading from vRA 7.0.1 to 7.5. Everything works (almost) perfectly in the old version, and I am getting a few strange errors on the new version.

* in kitchen, i get:
`Failed to complete #converge action: [key not found: :hostname] on master-Windows`
* using Terraform:
`last error: http response error: 400 - invalid content type`
* and running `knife vra catalog list`:
  ```
  FATAL: Unknown resource error : undefined method `downcase' for nil:NilClass
  ERROR: knife encountered an unexpected error
  This may be a bug in the 'vra catalog list' knife command or plugin
  Please collect the output of this command with the `-VVV` option before filing a bug report.
  Exception: NoMethodError: undefined method `downcase' for nil:NilClass
  ```

Versions:
```
ChefDK version: 4.5.0
Chef Infra Client version: 15.4.45
Chef InSpec version: 4.18.0
Test Kitchen version: 2.3.3
Foodcritic version: 16.1.1
Cookstyle version: 5.9.3
```
```
knife-acl (1.0.3)
knife-azure (2.0.2)
knife-cloud (2.0.3, 1.2.3)
knife-ec2 (1.0.16)
knife-google (4.2.0)
knife-opc (0.4.1)
knife-push (1.1.2)
knife-spork (1.7.2)
knife-tidy (2.0.1)
knife-vrealize (4.0.4, 4.0.3, 2.0.0)
knife-vsphere (4.0.3)
knife-windows (3.0.3, 1.9.6)
kitchen-vra (2.6.0)
vmware-vra (2.7.1)
```

VRealize:
`Version: 7.5.0 (Build: 10053500)`

**Comment by mcascone** [comment]
Here's another error:

```
~\Documents\github> knife vra catalog list
C:/opscode/chefdk/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': Win32API is deprecated after Ruby 1.9.1; use fiddle directly instead (StructuredWarnings::StandardWarning)
FATAL: Unknown resource error : undefined method `downcase' for nil:NilClass
ERROR: knife encountered an unexpected error
This may be a bug in the 'vra catalog list' knife command or plugin
Please collect the output of this command with the `-VVV` option before filing a bug report.
Exception: NoMethodError: undefined method `downcase' for nil:NilClass
~\Documents\github>
```

**Comment by mcascone** [comment]
I found [this on StackOverflow](https://stackoverflow.com/a/18902079/556078):

> When you see "undefined method ... for nil:NilClass" it means you have a nil value you're trying to call the method on.
In this case, something like data['name'] is not defined.
To make this more bullet-proof:
`data['name'].to_s.downcase.gsub(/\s+/, '')`
This converts everything to string to start with. nil.to_s is an empty string by default, so it's safe.

**Comment by mcascone** [comment]
Here's the output with `-VVV` enabled:
```
knife : C:/opscode/chefdk/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': Win32API is deprecated after Ruby 1.9.1; use fiddle 
directly instead (StructuredWarnings::StandardWarning)
At line:1 char:1
+ knife vra catalog list -VVV >  .\knifelog.txt 2>&1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (C:/opscode/chef...tandardWarning):String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
INFO: Using configuration from C:/Users/mcascone.CONSILIO/.chef/knife.rb
FATAL: Unknown resource error : undefined method `downcase' for nil:NilClass

C:/Users/mcascone.CONSILIO/AppData/Local/chefdk/gem/ruby/2.6.0/gems/knife-vrealize-4.0.4/lib/chef/knife/vra_catalog_list.rb:59:in `format_status_value
': undefined method `downcase' for nil:NilClass (NoMethodError)

	from C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/knife-cloud-2.0.3/lib/chef/knife/cloud/list_resource_command.rb:63:in `call'

	from C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/knife-cloud-2.0.3/lib/chef/knife/cloud/list_resource_command.rb:63:in `block in 
get_resource_col_val'
	from C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/knife-cloud-2.0.3/lib/chef/knife/cloud/list_resource_command.rb:62:in `each'

	from C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/knife-cloud-2.0.3/lib/chef/knife/cloud/list_resource_command.rb:62:in `get_resource_col_val'

	from C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/knife-cloud-2.0.3/lib/chef/knife/cloud/list_resource_command.rb:83:in `block in list'
	from C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/knife-cloud-2.0.3/lib/chef/knife/cloud/list_resource_command.rb:79:in `each'

	from C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/knife-cloud-2.0.3/lib/chef/knife/cloud/list_resource_command.rb:79:in `list'

	from C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/knife-cloud-2.0.3/lib/chef/knife/cloud/list_resource_command.rb:38:in `execute_command'

	from C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/knife-cloud-2.0.3/lib/chef/knife/cloud/command.rb:50:in `run'

	from C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.4.45-universal-mingw32/lib/chef/knife.rb:485:in `block in run_with_pretty_exceptions'

	from C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.4.45-universal-mingw32/lib/chef/local_mode.rb:42:in `with_server_connectivity'

	from C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.4.45-universal-mingw32/lib/chef/knife.rb:484:in `run_with_pretty_exceptions'

	from C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.4.45-universal-mingw32/lib/chef/knife.rb:228:in `run'

	from C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.4.45-universal-mingw32/lib/chef/application/knife.rb:162:in `run'

	from C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.4.45-universal-mingw32/bin/knife:24:in `<top (required)>'

	from C:/opscode/chefdk/bin/knife:366:in `load'
	from C:/opscode/chefdk/bin/knife:366:in `<main>'
```

**Comment by mcascone** [comment]
Is anybody monitoring these issues? @tas50 @adamleff

**Comment by akulbe** [comment]
We are experiencing the same issue here. I attempted to apply the suggested fixes here, and build-n-install the new gem… and I still hit the same error message.

**Comment by mcascone** [comment]
@akulbe @riccardopulcini I figured it out... i'm aggravated it's so simple. As mentioned in the docs, you can add `--entitled` to the command... i tried it and it works.

```
knife vra catalog list --entitled
```

No idea why it doesn't hit the `downCase` issue, but it looks like i'm enabled now.

**Comment by dheerajd-msys** [comment]
@riccardopulcini Please confirm if comment above helped you too https://github.com/chef/knife-vrealize/issues/44#issuecomment-609972465
